ALTER TABLE DBRoutine ADD COLUMN descripcion VARCHAR;
ALTER TABLE DBRoutine ADD COLUMN userId INTEGER;
ALTER TABLE DBRoutine ADD COLUMN hour INTEGER;
ALTER TABLE DBRoutine ADD COLUMN minute INTEGER;
ALTER TABLE DBRoutine ADD COLUMN minute INTEGER;
CREATE TABLE DiaEnum(day VARCHAR);
CREATE TABLE Routine_day(IdRoutine INTEGER, day VARCHAR)
CREATE TABLE Routine_devices(IdRoutine INTEGER, IdDevice INTEGER)
INSERT INTO DiaEnum (day) VALUES ("SUNDAY");
INSERT INTO DiaEnum (day) VALUES ("MONDAY");
INSERT INTO DiaEnum (day) VALUES ("TUESDAY");
INSERT INTO DiaEnum (day) VALUES ("WEDNESDAY");
INSERT INTO DiaEnum (day) VALUES ("THURSDAY");
INSERT INTO DiaEnum (day) VALUES ("FRIDAY");
INSERT INTO DiaEnum (day) VALUES ("SATURDAY");