logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-72-155-238.eu-west-1.compute.amazonaws.com:5432/d8rdmjobe6mfbb?user=jlwiyyrlxzwrjg&password=e29b2b05af7e550e2aaac427752414b8801dad5edc069a126daf8f65bc28540d&sslmode=require
    username: jlwiyyrlxzwrjg
    password: e29b2b05af7e550e2aaac427752414b8801dad5edc069a126daf8f65bc28540d
    max-active: 4
    max-idle: 2
    max-wait: 10000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    log-abandoned: true
    validation-query: SELECT 1
    generate-ddl: true
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      use-sql-comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
project:
  jwt:
    signKey: Bu:GW8bgPlEw
    expirationMinutes: 1440
