logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-211-158-144.eu-west-1.compute.amazonaws.com:5432/d6r1vf4b90ei0o?user=iavtzqavbajxsi&password=b4a0841b405ca149e78f731ceff90837be243ac8d4c0d56bf866925d93bf9300&sslmode=require
    username: iavtzqavbajxsi
    password: b4a0841b405ca149e78f731ceff90837be243ac8d4c0d56bf866925d93bf9300
    max-active: 4
    max-idle: 2
    max-wait: 10000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    log-abandoned: true
    validation-query: SELECT 1
    generate-ddl: true
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      use-sql-comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
project:
  jwt:
    signKey: Bu:GW8bgPlEw
    expirationMinutes: 1440
